export const FAKE_EMAILS_DATA = [
  {
    id: 0,
    status: 'INBOX',
    from: 'faulknerrichard@olucore.com',
    read: true,
    contactName: 'Cassie Knowles',
    avatar: 'https://i.pravatar.cc/150',
    email: 'cassieknowles@olucore.com',
    body: 'Pariatur commodo magna deserunt anim exercitation est. Sint laborum dolore in laboris ullamco. Irure qui excepteur Lorem irure qui officia pariatur. Adipisicing mollit officia excepteur ex enim ullamco ad voluptate veniam incididunt laboris dolor enim. Ut adipisicing laboris amet duis aute occaecat et officia culpa reprehenderit magna. Cupidatat est veniam eu aute veniam minim proident qui minim est consequat pariatur culpa irure.\r\nLorem dolor quis eu anim. Reprehenderit fugiat do magna reprehenderit. Id ea esse eiusmod et culpa pariatur dolor qui officia nostrud duis.\r\n',
    subject:
      'Excepteur non qui ex consequat consectetur labore cupidatat esse qui occaecat sunt dolore aliqua.',
    date: '2022-01-02',
  },
  {
    id: 1,
    status: 'SENT',
    from: 'me@gmail.com',
    read: true,
    contactName: 'Vous-même',
    avatar: 'https://i.pravatar.cc/150?u=me@gmail.com',
    email: 'cassieknowles@olucore.com',
    body: 'Nostrud deserunt aliqua duis aliquip exercitation adipisicing magna irure esse id. Ipsum id sit sit laborum do do officia esse ipsum Lorem dolor ad nisi qui. Irure ea esse veniam officia. Officia aute minim ut dolore.\r\nAd pariatur exercitation ut excepteur tempor aute ea magna exercitation ut ut. Amet proident sunt occaecat dolor voluptate. Velit dolore incididunt fugiat voluptate do in dolor eu. Pariatur id deserunt ea voluptate do quis. Mollit laborum exercitation sint consectetur. Duis sint incididunt deserunt dolore.\r\n',
    subject: 'Ipsum pariatur culpa eu laborum irure ut.',
    date: '2021-06-11',
  },
  {
    id: 2,
    status: 'TRASH',
    from: 'cassieknowles@olucore.com',
    read: true,
    contactName: 'Dodson Church',
    avatar: 'https://i.pravatar.cc/150',
    email: 'dodsonchurch@olucore.com',
    body: 'In est et cillum ad excepteur pariatur in dolore ad excepteur Lorem laborum adipisicing officia. Excepteur sit laborum enim minim mollit consequat velit nostrud anim laborum. Incididunt consequat id anim duis tempor tempor consequat ut labore eiusmod irure dolore occaecat. Duis minim proident do consectetur veniam sunt deserunt sunt fugiat.\r\nTempor anim excepteur pariatur dolore commodo. Amet consequat cillum magna aliqua. Proident ad excepteur officia fugiat quis adipisicing est laboris ullamco minim. Eiusmod cillum consequat fugiat id dolor do.\r\n',
    subject:
      'Aliqua ad Lorem est ut sunt aute excepteur consequat laborum exercitation aliquip in adipisicing.',
    date: '2021-10-06',
  },
  {
    id: 3,
    status: 'TRASH',
    from: 'dodsonchurch@olucore.com',
    read: false,
    contactName: 'Harriet Cruz',
    avatar: 'https://i.pravatar.cc/150',
    email: 'harrietcruz@olucore.com',
    body: 'Labore laborum reprehenderit cupidatat sit sunt elit qui esse aliqua est mollit duis officia. Laborum velit dolore reprehenderit commodo commodo officia proident nostrud. Officia eiusmod et amet duis.\r\nIpsum officia nostrud amet labore dolor est non ad aliquip ex cillum. Duis ex ipsum proident nulla voluptate nostrud ullamco dolor fugiat quis. Ad fugiat pariatur laboris fugiat aliqua magna duis laborum reprehenderit pariatur. Nulla fugiat ea occaecat tempor est sunt fugiat anim nostrud adipisicing. Fugiat sint incididunt laboris pariatur officia duis sunt voluptate. Exercitation ea consectetur ex adipisicing aliquip irure voluptate proident laborum occaecat tempor.\r\n',
    subject: 'Sint occaecat esse anim ex ullamco duis.',
    date: '2020-05-11',
  },
  {
    id: 4,
    status: 'SENT',
    from: 'me@gmail.com',
    read: true,
    contactName: 'Vous-même',
    avatar: 'https://i.pravatar.cc/150?u=me@gmail.com',
    email: 'harrietcruz@olucore.com',
    body: 'Ut et quis irure amet in veniam et elit nostrud qui deserunt. Enim laborum sint adipisicing quis mollit. Aliqua reprehenderit Lorem ex do dolor cillum nisi ut amet dolore laboris. Excepteur laborum qui sit do occaecat culpa duis esse velit qui sit non qui excepteur.\r\nOfficia cillum sunt consequat consectetur fugiat cillum aliquip adipisicing incididunt sunt aliqua deserunt deserunt. Cillum commodo et anim eiusmod amet amet ea sint et labore nisi laboris. Esse excepteur est cupidatat sit amet occaecat.\r\n',
    subject:
      'Sunt eu aliqua eu irure fugiat incididunt consectetur minim veniam nulla est dolore.',
    date: '2021-10-29',
  },
  {
    id: 5,
    status: 'TRASH',
    from: 'harrietcruz@olucore.com',
    read: true,
    contactName: 'Elma Stafford',
    avatar: 'https://i.pravatar.cc/150',
    email: 'elmastafford@olucore.com',
    body: 'Cillum aliqua ea commodo proident elit et eu irure minim et Lorem sunt ex magna. Ea labore sint enim minim commodo ipsum officia sint qui sunt non duis. Adipisicing consectetur commodo ipsum nostrud id cillum elit et ut. Cupidatat nisi est adipisicing commodo laborum ullamco anim voluptate enim culpa adipisicing.\r\nTempor id aliqua laborum ad excepteur aliqua aliqua aute nisi duis mollit reprehenderit do sint. Laboris cillum cillum aute exercitation deserunt ea duis labore tempor sint et. Reprehenderit velit amet id nostrud dolore pariatur tempor nostrud non nostrud fugiat velit.\r\n',
    subject:
      'Irure reprehenderit ea laborum ea esse proident do ullamco anim sint laborum elit.',
    date: '2022-07-30',
  },
  {
    id: 6,
    status: 'SENT',
    from: 'me@gmail.com',
    read: true,
    contactName: 'Vous-même',
    avatar: 'https://i.pravatar.cc/150?u=me@gmail.com',
    email: 'elmastafford@olucore.com',
    body: 'Irure occaecat pariatur eu occaecat elit. Ipsum aute deserunt excepteur deserunt deserunt. Officia fugiat est esse laborum Lorem laborum duis dolore fugiat. Cillum cillum excepteur minim Lorem excepteur nulla eu consectetur duis non anim laborum ea ullamco.\r\nEst exercitation ipsum ea eiusmod elit. Est et eiusmod anim nulla consequat ipsum ea nisi Lorem voluptate sint. Culpa cillum ex veniam minim ea reprehenderit laboris.\r\n',
    subject: 'Do esse aute anim magna esse.',
    date: '2021-02-14',
  },
  {
    id: 7,
    status: 'INBOX',
    from: 'elmastafford@olucore.com',
    read: true,
    contactName: 'Sarah Ellis',
    avatar: 'https://i.pravatar.cc/150',
    email: 'sarahellis@olucore.com',
    body: 'Fugiat laboris quis reprehenderit veniam consequat anim Lorem. Labore laboris magna labore consequat laborum mollit amet adipisicing aliquip deserunt ullamco consequat nisi ipsum. Laborum esse esse tempor mollit. Minim dolore quis velit in proident ipsum eu.\r\nSint culpa nostrud deserunt ex pariatur anim sint exercitation. Quis excepteur duis Lorem laboris. Enim elit et eu exercitation cupidatat adipisicing aliquip minim ad excepteur esse ea in eu. Aute id pariatur ad cupidatat consequat duis ut ipsum. Minim eu cupidatat occaecat aliquip. Aliqua fugiat esse reprehenderit proident sint minim velit officia enim. Deserunt reprehenderit culpa consequat nisi.\r\n',
    subject:
      'Excepteur ut ea do enim aliqua sunt voluptate culpa Lorem dolore enim nostrud cillum.',
    date: '2020-09-04',
  },
  {
    id: 8,
    status: 'SENT',
    from: 'me@gmail.com',
    read: true,
    contactName: 'Vous-même',
    avatar: 'https://i.pravatar.cc/150?u=me@gmail.com',
    email: 'sarahellis@olucore.com',
    body: 'Consectetur exercitation occaecat amet dolore sunt aliquip sint irure ullamco. Nulla incididunt incididunt do irure consequat dolor. Dolor nisi exercitation reprehenderit reprehenderit officia aute laborum est proident. Veniam nisi voluptate sit officia esse anim culpa exercitation voluptate id occaecat. Reprehenderit nulla ex enim duis dolore in aute aliqua dolore mollit excepteur sit. Lorem exercitation adipisicing velit exercitation aliquip nostrud cillum id eu velit quis fugiat. Officia cupidatat ex dolore labore laboris tempor eu mollit qui.\r\nCommodo anim eu officia dolore laborum tempor cupidatat ad. Occaecat adipisicing duis mollit voluptate. Lorem eu ad consequat nostrud velit esse ut Lorem aliquip ex do aute ea. Esse ad esse incididunt consectetur.\r\n',
    subject: 'In qui enim quis aliquip ipsum nisi mollit non consequat non.',
    date: '2020-03-12',
  },
  {
    id: 9,
    status: 'SENT',
    from: 'me@gmail.com',
    read: true,
    contactName: 'Vous-même',
    avatar: 'https://i.pravatar.cc/150?u=me@gmail.com',
    email: 'sarahellis@olucore.com',
    body: 'Excepteur velit non cillum ea laborum nisi duis Lorem sunt eiusmod. Aute ea anim ad culpa et amet do. Occaecat duis nulla in nostrud minim nisi ex ex duis. Anim esse et sit sit ex dolor nisi ex. Tempor sint amet dolor exercitation reprehenderit tempor cupidatat sint do do commodo laboris.\r\nVelit irure excepteur sit quis qui laborum exercitation velit cupidatat. Magna aute dolore fugiat ad aute adipisicing nulla. Labore non esse fugiat esse cillum excepteur commodo nisi amet do reprehenderit voluptate non. Reprehenderit proident sint fugiat ex pariatur do velit laboris. Adipisicing dolor reprehenderit sint velit incididunt. Deserunt laboris ad laboris laborum pariatur sunt labore.\r\n',
    subject:
      'Pariatur nostrud in nulla dolore voluptate sunt exercitation consectetur do ullamco excepteur laboris elit.',
    date: '2020-12-04',
  },
  {
    id: 10,
    status: 'INBOX',
    from: 'sarahellis@olucore.com',
    read: false,
    contactName: 'Lizzie Reeves',
    avatar: 'https://i.pravatar.cc/150',
    email: 'lizziereeves@olucore.com',
    body: 'Laboris id mollit eu non. Irure sint magna veniam sint. Adipisicing voluptate nisi voluptate consectetur ex id enim est et occaecat. Nostrud nostrud sint sit magna minim incididunt adipisicing magna. Officia irure duis ad anim laboris elit ipsum eiusmod laboris irure amet culpa. Enim cupidatat eu cupidatat mollit ea voluptate eu veniam mollit proident. Consequat Lorem reprehenderit magna nulla laborum laboris eu non.\r\nAliquip consectetur excepteur qui proident occaecat ipsum sint sint pariatur ullamco. Do eiusmod consectetur minim duis ullamco nostrud consectetur. Ad ullamco minim est ex sint consequat eu sint magna magna voluptate magna ad Lorem. Ad sit duis enim qui ex nostrud. Nulla eiusmod ipsum in aliquip culpa in aliqua reprehenderit fugiat ipsum ut sunt.\r\n',
    subject: 'Elit non ut esse consequat quis.',
    date: '2021-03-22',
  },
  {
    id: 11,
    status: 'TRASH',
    from: 'lizziereeves@olucore.com',
    read: false,
    contactName: 'Constance Henderson',
    avatar: 'https://i.pravatar.cc/150',
    email: 'constancehenderson@olucore.com',
    body: 'Anim anim consectetur consequat amet cupidatat officia quis irure est quis aliqua cupidatat voluptate amet. Commodo nostrud pariatur non do veniam aliqua dolore incididunt. Ad esse sint Lorem reprehenderit.\r\nNostrud mollit minim commodo adipisicing velit tempor cupidatat do. Duis culpa incididunt tempor ad dolor sunt ut voluptate commodo reprehenderit proident dolor enim enim. Laborum consectetur Lorem sint consequat ex laboris esse mollit reprehenderit. Ipsum qui ea amet aliquip excepteur aliqua officia minim quis. Labore culpa fugiat ea irure proident reprehenderit et exercitation reprehenderit fugiat culpa. Irure do nisi dolore nisi officia nisi aute non duis reprehenderit do.\r\n',
    subject:
      'Ex commodo tempor consequat ut consectetur ad veniam eu ullamco proident elit adipisicing ipsum cupidatat.',
    date: '2021-04-17',
  },
  {
    id: 12,
    status: 'SENT',
    from: 'me@gmail.com',
    read: true,
    contactName: 'Vous-même',
    avatar: 'https://i.pravatar.cc/150?u=me@gmail.com',
    email: 'constancehenderson@olucore.com',
    body: 'Mollit voluptate dolore amet occaecat sit excepteur ad enim irure dolore excepteur aliqua. Esse Lorem eu eiusmod veniam. Lorem eu ullamco incididunt officia est eiusmod magna dolor veniam. Et ad proident ea esse.\r\nTempor incididunt consectetur esse qui esse nostrud ipsum enim esse id Lorem in non quis. Adipisicing in id dolor qui consequat elit reprehenderit laboris occaecat eu. Sit sunt velit exercitation aliqua non aute cupidatat occaecat nisi occaecat eiusmod ullamco. Irure deserunt commodo commodo est dolore duis duis officia mollit et irure. Nulla tempor ad reprehenderit ipsum consequat consequat mollit et ut cupidatat. Reprehenderit proident ex sunt cillum pariatur aliqua sunt magna labore cupidatat est sunt. Sunt amet cillum consectetur dolore aliqua magna deserunt fugiat id consequat deserunt sint.\r\n',
    subject: 'Excepteur elit ipsum exercitation aliquip velit.',
    date: '2021-03-20',
  },
  {
    id: 13,
    status: 'TRASH',
    from: 'constancehenderson@olucore.com',
    read: false,
    contactName: 'Berta Munoz',
    avatar: 'https://i.pravatar.cc/150',
    email: 'bertamunoz@olucore.com',
    body: 'Irure consectetur non amet et esse culpa in do eiusmod officia enim sint velit. Ipsum ea aliquip aute ex consequat consectetur laboris. Anim adipisicing amet laborum culpa elit id.\r\nCommodo do laborum quis ipsum eu dolor in non incididunt duis. Duis ea qui velit ea amet dolore. Sit minim irure dolore sunt non ut consectetur anim cupidatat duis dolore incididunt consequat.\r\n',
    subject:
      'Culpa esse ad ex deserunt veniam anim in occaecat ipsum consectetur esse.',
    date: '2021-05-22',
  },
  {
    id: 14,
    status: 'SENT',
    from: 'me@gmail.com',
    read: true,
    contactName: 'Vous-même',
    avatar: 'https://i.pravatar.cc/150?u=me@gmail.com',
    email: 'bertamunoz@olucore.com',
    body: 'Cupidatat cillum in anim veniam non. Do esse nisi adipisicing voluptate aliquip dolore ipsum aliqua. Laborum ut cillum do ad et aute. Dolor fugiat id dolore nisi ea sint ullamco irure officia excepteur velit occaecat tempor. Ullamco irure sit esse in consectetur ex. Cupidatat sunt sit ipsum duis proident cillum elit minim. Anim irure ipsum proident id velit velit Lorem.\r\nNulla anim officia voluptate sint ut. Do laborum culpa enim ea irure reprehenderit excepteur labore mollit incididunt. Sint adipisicing quis officia exercitation nisi proident aliquip nulla aute consequat. Aliquip culpa sunt elit laboris veniam dolor eu ex nisi aute eu velit irure reprehenderit. Sint aliqua ex veniam nulla sunt consectetur labore cupidatat. Ea velit irure aute quis aliquip dolore et proident aliqua culpa esse fugiat. Elit mollit deserunt duis voluptate.\r\n',
    subject: 'Laborum ut in deserunt exercitation anim aliqua fugiat.',
    date: '2022-06-30',
  },
  {
    id: 15,
    status: 'SENT',
    from: 'me@gmail.com',
    read: true,
    contactName: 'Vous-même',
    avatar: 'https://i.pravatar.cc/150?u=me@gmail.com',
    email: 'bertamunoz@olucore.com',
    body: 'Do do sunt cupidatat sunt do eiusmod ad dolor anim culpa commodo deserunt. Exercitation dolor ex duis eu consectetur consequat culpa. Amet laborum proident qui aliquip nisi nisi Lorem incididunt est qui cupidatat cillum voluptate. Cillum pariatur cillum est irure dolore. Est ullamco minim et cillum reprehenderit occaecat esse sit consequat aliqua ullamco mollit ea ea.\r\nPariatur dolor id amet ea cillum amet. Esse tempor eiusmod aliquip voluptate nisi Lorem veniam in officia nisi consequat veniam. Minim culpa deserunt pariatur esse officia ut amet.\r\n',
    subject:
      'Mollit nisi nulla sint et sint ullamco adipisicing ad officia cupidatat occaecat.',
    date: '2021-04-29',
  },
  {
    id: 16,
    status: 'TRASH',
    from: 'bertamunoz@olucore.com',
    read: false,
    contactName: 'King Murray',
    avatar: 'https://i.pravatar.cc/150',
    email: 'kingmurray@olucore.com',
    body: 'Pariatur do id officia sint pariatur commodo laboris enim magna aliqua tempor exercitation ea. Quis in minim deserunt deserunt quis Lorem dolor velit adipisicing. Labore deserunt do aute veniam dolore et quis cillum.\r\nLaboris deserunt incididunt laboris exercitation officia sunt culpa consectetur anim. In id fugiat ut ipsum occaecat. Labore proident duis duis officia non culpa.\r\n',
    subject: 'Proident sint magna exercitation labore fugiat ex.',
    date: '2020-05-07',
  },
  {
    id: 17,
    status: 'INBOX',
    from: 'kingmurray@olucore.com',
    read: true,
    contactName: 'Merrill Hurley',
    avatar: 'https://i.pravatar.cc/150',
    email: 'merrillhurley@olucore.com',
    body: 'Minim ad ex elit laboris excepteur ut voluptate ad aute do. Nulla dolore ad tempor irure adipisicing cillum non. Elit aliqua dolor qui nulla non. Esse ut anim proident nulla nisi amet excepteur sit voluptate. Consectetur dolore veniam magna officia in dolore qui fugiat officia anim.\r\nFugiat cupidatat ipsum fugiat est anim cupidatat aliqua exercitation minim adipisicing. Ex aute quis aute proident incididunt minim duis. Fugiat aliquip commodo voluptate aliqua officia. Ullamco culpa tempor deserunt culpa enim quis laborum aliquip ut tempor sint. Amet magna non ullamco duis.\r\n',
    subject:
      'Exercitation consequat nulla duis id consequat laboris irure qui sit reprehenderit.',
    date: '2022-11-22',
  },
  {
    id: 18,
    status: 'INBOX',
    from: 'merrillhurley@olucore.com',
    read: false,
    contactName: 'Goff Johnston',
    avatar: 'https://i.pravatar.cc/150',
    email: 'goffjohnston@olucore.com',
    body: 'Veniam aliqua irure incididunt aliquip tempor deserunt dolore cupidatat fugiat. Irure minim aliquip sint reprehenderit duis consequat. Qui nisi sint et proident esse id et sit sit dolore. Ex voluptate velit eu cillum laboris ad mollit dolore commodo elit excepteur mollit dolore. Aute eu cupidatat pariatur cillum laboris est laboris et excepteur voluptate. Laboris occaecat nostrud officia velit irure cupidatat.\r\nDuis cillum mollit deserunt enim aliquip adipisicing consectetur deserunt sit nulla qui cupidatat labore. Nulla do non ut excepteur esse aliqua occaecat occaecat labore consequat sunt veniam. Aliqua laboris incididunt excepteur voluptate do occaecat ad ut anim.\r\n',
    subject:
      'Magna laboris pariatur officia nostrud nisi proident esse mollit proident qui excepteur voluptate quis.',
    date: '2022-10-25',
  },
  {
    id: 19,
    status: 'TRASH',
    from: 'goffjohnston@olucore.com',
    read: false,
    contactName: 'Norma Daniels',
    avatar: 'https://i.pravatar.cc/150',
    email: 'normadaniels@olucore.com',
    body: 'Incididunt mollit occaecat ex nisi id proident mollit tempor labore labore in amet amet et. Fugiat mollit occaecat officia do ea adipisicing officia ea aliqua eu enim veniam voluptate aliqua. Cupidatat sint duis deserunt ea proident eiusmod do sit nulla id cupidatat excepteur cupidatat. Dolore cillum tempor laboris excepteur magna tempor deserunt laboris. Adipisicing laborum occaecat irure commodo aute id culpa eu. Culpa amet aliqua ad cillum laboris duis. Esse dolor nostrud adipisicing proident eu laborum.\r\nDo fugiat proident magna sint irure cillum cupidatat ad. Proident sunt ut cupidatat nostrud elit velit quis labore non reprehenderit eu. Deserunt incididunt aute velit voluptate enim dolore fugiat. Ad sint velit duis cillum ea nisi exercitation duis laborum officia culpa irure. Voluptate ex ut dolor consectetur deserunt. Amet velit sint ut sit et magna exercitation cupidatat qui nulla amet. Sint tempor duis proident laborum proident pariatur aliquip proident sit enim incididunt incididunt tempor voluptate.\r\n',
    subject:
      'Occaecat ex et laboris cupidatat ullamco do laboris esse commodo consequat non sit.',
    date: '2020-11-07',
  },
  {
    id: 20,
    status: 'TRASH',
    from: 'normadaniels@olucore.com',
    read: false,
    contactName: 'Lyons Vance',
    avatar: 'https://i.pravatar.cc/150',
    email: 'lyonsvance@olucore.com',
    body: 'Consequat ipsum qui voluptate id amet Lorem sit. Incididunt esse cillum ex consequat dolor adipisicing. Aliquip commodo voluptate magna est esse culpa elit elit cillum non. Mollit est eu voluptate tempor Lorem in commodo in. Quis commodo sint consequat voluptate minim consequat velit occaecat officia anim duis sunt cupidatat. Anim reprehenderit occaecat commodo cupidatat dolore dolore elit nostrud cillum pariatur ad non consectetur.\r\nAd magna aute duis aliquip amet incididunt excepteur mollit. Nostrud esse anim ex aute consectetur enim incididunt ea consectetur voluptate labore consequat. Reprehenderit culpa ut excepteur voluptate duis anim cupidatat cupidatat ad mollit eu. Ad pariatur ex nisi consectetur eu veniam labore est.\r\n',
    subject: 'Sunt consectetur officia consectetur proident culpa deserunt.',
    date: '2021-04-22',
  },
  {
    id: 21,
    status: 'INBOX',
    from: 'lyonsvance@olucore.com',
    read: false,
    contactName: 'Sallie Blake',
    avatar: 'https://i.pravatar.cc/150',
    email: 'sallieblake@olucore.com',
    body: 'Lorem ad do culpa quis sit in eu irure laboris laboris. Excepteur sint enim anim non exercitation duis ex irure officia. Ex culpa aliqua irure commodo aliqua voluptate cupidatat veniam. Id in exercitation in occaecat laborum et nisi duis enim aliquip ex.\r\nDuis consectetur tempor esse consectetur magna consectetur proident enim occaecat in. Anim ipsum pariatur ut amet. Eiusmod Lorem aliqua eu velit nostrud incididunt laborum eu nostrud laboris aliqua.\r\n',
    subject: 'Laboris magna minim Lorem id qui.',
    date: '2020-12-13',
  },
  {
    id: 22,
    status: 'SENT',
    from: 'me@gmail.com',
    read: true,
    contactName: 'Vous-même',
    avatar: 'https://i.pravatar.cc/150?u=me@gmail.com',
    email: 'sallieblake@olucore.com',
    body: 'Do cupidatat deserunt est do veniam esse culpa incididunt sunt aute deserunt eiusmod deserunt sint. Eu ipsum officia id dolor veniam laboris minim aute in sint. Officia ea fugiat ut mollit pariatur aliquip.\r\nLaborum consectetur est aliqua fugiat ut voluptate incididunt. Anim non aliquip ea reprehenderit esse commodo ut sunt consectetur excepteur ea laboris cupidatat non. Ad commodo laboris veniam non in amet proident exercitation enim culpa tempor proident. Dolor elit officia culpa aliqua cupidatat in mollit irure id incididunt. Veniam id excepteur dolor elit commodo tempor quis in nisi in.\r\n',
    subject: 'Cillum est cupidatat nostrud sint minim.',
    date: '2020-03-12',
  },
  {
    id: 23,
    status: 'TRASH',
    from: 'sallieblake@olucore.com',
    read: true,
    contactName: 'Mack Diaz',
    avatar: 'https://i.pravatar.cc/150',
    email: 'mackdiaz@olucore.com',
    body: 'Cupidatat do qui laborum do adipisicing amet sint ullamco do veniam non ullamco. Non ipsum aliquip sint veniam ut nisi ipsum laboris veniam occaecat duis. Est reprehenderit ex est ullamco duis labore nostrud adipisicing qui aute. Sit occaecat enim fugiat ipsum Lorem dolore. Esse cupidatat ut voluptate nulla laboris aliqua. Id excepteur tempor dolor laboris sint id Lorem enim.\r\nUt minim fugiat ea fugiat aute aute labore in exercitation culpa ipsum. Fugiat enim reprehenderit amet commodo. Laborum sunt exercitation incididunt ad amet. Consectetur incididunt non do consectetur sint ipsum occaecat reprehenderit incididunt mollit commodo eu.\r\n',
    subject: 'Sunt adipisicing enim occaecat Lorem occaecat.',
    date: '2021-12-05',
  },
  {
    id: 24,
    status: 'INBOX',
    from: 'mackdiaz@olucore.com',
    read: false,
    contactName: 'Ana Rosario',
    avatar: 'https://i.pravatar.cc/150',
    email: 'anarosario@olucore.com',
    body: 'Cupidatat ut cillum aute aliquip proident ut do ex adipisicing velit dolore voluptate reprehenderit sit. Cillum duis adipisicing adipisicing sunt irure deserunt ipsum dolor aute amet ea irure fugiat mollit. Cupidatat minim adipisicing esse ut reprehenderit culpa quis velit deserunt dolor cupidatat nisi est velit. Ex occaecat deserunt sint ea non sit nulla irure duis amet elit cillum. Magna cupidatat anim Lorem minim id exercitation minim magna reprehenderit nulla voluptate nulla. Ullamco Lorem et officia elit non nulla laboris consectetur minim proident et labore ut enim. Enim sit consectetur mollit sunt.\r\nEa ut ullamco elit dolore magna qui ea tempor ipsum nisi officia. Incididunt est exercitation id ipsum labore magna dolor. Nostrud ipsum ullamco nulla magna est deserunt Lorem. Nostrud ea elit labore culpa sit cillum duis. Consequat duis commodo aute velit minim. Qui id in sunt id ipsum ad anim cillum eiusmod ullamco duis irure nostrud non.\r\n',
    subject:
      'Occaecat voluptate culpa quis anim labore eu occaecat et sunt reprehenderit voluptate.',
    date: '2020-07-14',
  },
];
